import React, { useState, useEffect, useCallback } from 'react';
import ControlPanel from './components/ControlPanel';
import PreviewCanvas from './components/PreviewCanvas';
import { NeonConfig, PathData, AVAILABLE_FONTS } from './types';
import { generateCenterline, generateCenterlineFromImage } from './services/vectorizer';

const App: React.FC = () => {
  // Initial State
  const [config, setConfig] = useState<NeonConfig>({
    mode: 'text',
    text: 'Neon',
    image: null,
    fontFamily: AVAILABLE_FONTS[0].name,
    color: '#FF00FF',
    backgroundColor: '#000000',
    backgroundTexture: 'brick',
    fontSize: 150,
    blur: 4,
    smoothing: 20, 
    threshold: 128,
    gapMergeDistance: 0 // Default 0
  });

  const [paths, setPaths] = useState<PathData[]>([]);
  const [isProcessing, setIsProcessing] = useState(false);

  // Debounced processing
  useEffect(() => {
    const timer = setTimeout(async () => {
      setIsProcessing(true);
      try {
        let generatedPaths: PathData[] = [];

        if (config.mode === 'text') {
            if (config.text.trim()) {
                generatedPaths = await generateCenterline(
                    config.text, 
                    config.fontFamily, 
                    800, // Canvas Width
                    300, // Canvas Height
                    150, // Font Size
                    config.smoothing,
                    config.gapMergeDistance
                );
            }
        } else if (config.mode === 'image' && config.image) {
            generatedPaths = await generateCenterlineFromImage(
                config.image,
                800,
                300,
                config.threshold,
                config.smoothing,
                config.gapMergeDistance
            );
        }
        
        setPaths(generatedPaths);
      } catch (error) {
        console.error("Vectorization failed", error);
      } finally {
        setIsProcessing(false);
      }
    }, 500); 

    return () => clearTimeout(timer);
  }, [config.text, config.fontFamily, config.smoothing, config.mode, config.image, config.threshold, config.gapMergeDistance]);

  const handleExport = useCallback(() => {
    if (paths.length === 0) return;

    // Create SVG content with proper Bezier paths
    const svgContent = `
<svg xmlns="http://www.w3.org/2000/svg" width="800" height="300" viewBox="0 0 800 300">
  <!-- Generated by Neon Vector Builder -->
  <!-- Centerline paths for CNC -->
  <g fill="none" stroke="red" stroke-width="1" stroke-linecap="round" stroke-linejoin="round">
    ${paths.map(pathData => {
        let d = '';
        if (pathData.path) {
            d = pathData.path;
        } else {
            d = pathData.points.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(' ');
        }
        return `<path d="${d}" />`;
    }).join('\n    ')}
  </g>
</svg>`.trim();

    const blob = new Blob([svgContent], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `neon-${config.mode === 'text' ? config.text.replace(/[^a-z0-9]/gi, '_').toLowerCase() : 'image'}.svg`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [paths, config.text, config.mode]);

  return (
    <div className="flex flex-col md:flex-row-reverse h-screen w-full bg-gray-900 text-white font-sans overflow-hidden">
      {/* 
        Layout Strategy:
        Mobile: PreviewCanvas is first (Top), ControlPanel is second (Bottom).
        Desktop: flex-row-reverse makes PreviewCanvas (Right) and ControlPanel (Left).
      */}
      
      {/* Main Canvas Area */}
      <PreviewCanvas 
        config={config} 
        paths={paths} 
        isProcessing={isProcessing}
      />

      {/* Sidebar Controls */}
      <ControlPanel 
        config={config} 
        onChange={setConfig} 
        onExport={handleExport}
        isProcessing={isProcessing}
      />
    </div>
  );
};

export default App;